### ISSUE TITLE
How to handle "folders created/deleted after registration"?

### ISSUE THREAD

**Issue by ngocdaothanh** [lloydmeta/schwatcher#44]
In README:

> Callbacks that are registered with recursive=true are not persistently-recursive. That is, they do not propagate to new files or folders created/deleted after registration. Currently, the plan is to have developers handle this themselves in the callback functions.

Do you mean developers should unregister and register again inside the callback functions? Is there problem when `concurrency` > 1?

**Comment by pathikrit** [comment]
I think this worth reconsidering. Even Oracle's canonical example here: https://docs.oracle.com/javase/tutorial/essential/io/examples/WatchDir.java
 auto-registers a watcher on any new directories created inside the recursively watched directory.

Btw, I am the author of another implementation (https://github.com/pathikrit/better-files#file-watchers) of this based purely on Java threads: 
https://github.com/pathikrit/better-files/blob/master/src/main/scala/better/files/FileMonitor.scala
Please take a look if you have any time for suggestions/reviews. Thanks!

**Comment by lloydmeta** [comment]
@pathikrit thanks for the note; I've starred your repo since a while ago :)

I can't remember why I had left that for end-users to handle, but theoretically it looks simple enough to implement:

```java
// if directory is created, and watching recursively, then
                // register it and its sub-directories
                if (recursive && (kind == ENTRY_CREATE)) {
                    try {
                        if (Files.isDirectory(child, NOFOLLOW_LINKS)) {
                            registerAll(child);
                        }
                    } catch (IOException x) {
                        // ignore to keep sample readbale
                    }
                }
```

Just leaving a note on a possible implementation:

I think in this lib, this can be handled by having the watch path message (watchMsg1) have a `autoWatchNew` parameter that causes the actor to automatically register itself to file creation events down the file hierarchy in order to auto-register those for the same callback as in watchMsg1.
